### ISSUE TITLE
Center address thingy

### ISSUE THREAD

**Issue by zamli** [nimi-app/card#63]
Center the address thing so the whole row is centered

![Image](https://user-images.githubusercontent.com/25611956/185611545-2be528c3-f03e-416c-a2ca-1ec5b59ca7f4.png)

**Comment by daveai** [comment]
Center better when ENS domain is very long

![Image](https://user-images.githubusercontent.com/10086922/188424177-f6d3eb06-4343-4410-8851-8a86860b52de.png)

**Comment by adamazad** [comment]
No longer applicable
